server:
  port: 8080
  servlet:
    context-path: /hello
spring:
  datasource:
    url: jdbc:mysql://192.168.52.128:3306/hello_springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc123
    type: com.alibaba.druid.pool.DruidDataSource
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admim
  #默认情况下activemq提供的是queue模式，若要使用topic模式需要配置下面配置
  jms:
    pub-sub-domain: true
mybatis:
  type-aliases-package: com.yinjian.domain
  mapper-locations: classpath:mapper/*.xml